### PR TITLE
Update to nunit3 as appveyor is upgraded

### PR DESCRIPTION
**Pull request by kai-zeng**
This reverts commit e2bc271edb9174dbdb1f95c1438c60f2350a4d70.

### CODE REVIEW

**Comment by skaarthik** [comment]
Looks like @rapoth already reverted your change

**Comment by kai-zeng** [comment]
Yeah, so I want to test it again to see what's the problem. I tested it locally and it works fine.

**Comment by kai-zeng** [comment]
@rapoth It seems the build is passed. So what was the problem?

**Comment by rapoth** [comment]
Yes, this was the case before too. When I went ahead and completed the merge, it failed.

**Pull request merged**
