### PR TITLE
add packaging signing and deployment to maven central

### PR DESCRIPTION
**Pull request by danielli90**

### CODE REVIEW

**Comment by skaarthik** [comment]
Would it be possible to include in this PR the instructions for SparkCLR deployment use case (called out in issue #177) to get the story straight on how the published artifact will be used along with rest of the stuff we will be releasing (like submit script)?not sure about others but I do not have the complete picture on this.

**Comment by skaarthik** [comment]
Typo in the previous comment. I meant issue #199 (not #177)

**Comment by danielli90** [comment]
The instructions on how to release packages and how developers can use the packages will be next.

**Comment by qintao1976** [comment]
LGTM

**Pull request merged**
