### PR TITLE
Changed deprecated camelCase SQL function names to underscore format

### PR DESCRIPTION
**Pull request by adamante**
Issue #281 
My first PR ever. Let me know if something's wrong. I ran all the tests and samples.

### CODE REVIEW

**Comment by jthelin** [comment]
Hi @adamante. 
For context, could you provide a cross reference link to the corresponding Spark Sql syntax changes and/or deprecation info in the Apache Spark docs? 
Thanks,

**Comment by skaarthik** [comment]
@jthelin - https://github.com/apache/spark/commit/151d7c2baf18403e6e59e97c80c8bcded6148038

**Comment by skaarthik** [comment]
LGTM

**Comment by skaarthik** [comment]
Thanks for your contribution @adamante

**Pull request merged**
