### PR TITLE
Create a uber package to include all dependency

### PR DESCRIPTION
**Pull request by danielli90**
it increases the target sample jar from 154KBytes to 104MBytes, but it **removes** the error-prone manual processes in manually identify dependent  jars needed at run-time, and manually include those jars at SPARKCVS_JAR before submitting the job. this PR replaces #54 - which will not be merged in.

### CODE REVIEW

**Comment by danielli90** [comment]
replaced by another PR that squashes two commits into one

**Comment by jthelin** [comment]
BTW @danielli90 you don't have to create a new PR to do this type of "branch cleanup".

You can rebase/squash your local copy of the branch to whatever "final form" you want and then (force) push to the same branch name to update the original PR on GitHub.

That will just replace the change set to be merged for this PR but keep all the PR discussion history.

Most repos have their `master` branch set to prohibit forced pushes on that branch [and rightly so, IMHO -- should always merge to master, not rewrite] 
But it actually makes a lot of sense to do forced pushes on some long-running pull request / feature branches where lots of discussion & changes happened before the final stable code version is ready to merge in to master.

Many people have an automatic aversion to `git push --force` but it is actually a very useful function when used for the correct reasons. This is one of those "good" use cases ;)
HTH.

**Comment by danielli90** [comment]
Got it. Thanks @jthelin.

**Comment by danielli90** [comment]
Used @jthelin’s suggestion for PR#59 – “git push –force” worked magically.

Thx
Daniel

**Pull request closed without merging**
