### PR TITLE
Adding logo for SparkCLR and updating Readme.md

### PR DESCRIPTION
**Pull request by kspk**
Added logo for the project under the /logo folder. Logos available in multiple sizes and with white and transparent background. 

Updated README.md file to include the new logo in the header.

### CODE REVIEW

**Comment by skaarthik** [comment]
Thanks @kspk . Looks like "spark-clr-clear-100x40.png" actually has white background. Please update that.

**Comment by danielli90** [comment]
LGTM

**Comment by skaarthik** [comment]
closing the request and reopening to get CLA check run again

**Comment by skaarthik** [comment]
Thanks @kspk

**Pull request merged**
