### PR TITLE
add unit test for row and column under sql namespace

### PR DESCRIPTION
**Pull request by ms-guizha**

### CODE REVIEW

**Comment by skaarthik** [comment]
@ms-guizha - looks like there are some conflicts. Please fix so that we can merge your changes.

**Comment by ms-guizha** [comment]
@skaarthik I have solved the conflict before sending pull request

**Comment by ms-guizha** [comment]
could you help me try to close the pull request and then reopen as you did last time. I don not why the build is cancelled

**Comment by skaarthik** [comment]
Build happens automatically when you update the PR. Looks like both Windows and Linux builds are in progress now.

**Comment by skaarthik** [comment]
Great job, @ms-guizha . Code coverage is not 70.12%!

**Comment by jthelin** [comment]
Whoo. Nice job guys!

@skaarthik - s/not/now/ ;)

**Pull request merged**
